config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  resources :main_pages

  resources :products

  root 'main_pages#index'
get 'tags/:tag', to: 'products#index', as: :tag
end

app/models/main_page.rb
class MainPage < ActiveRecord::Base
end

app/models/product.rb
class Product < ActiveRecord::Base
	extend FriendlyId
	friendly_id :name, use: :slugged
	has_attached_file :image, :styles => { :medium => "300x300>", :thumb => "100x100>" }, :default_url => "/images/:style/missing.png"
  	validates_attachment_content_type :image, :content_type => /\Aimage\/.*\Z/
  	belongs_to :user
  	acts_as_taggable # Alias for acts_as_taggable_on :tags
  	acts_as_taggable_on :skills, :interests
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
  has_many :products
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/main_pages_controller.rb
class MainPagesController < ApplicationController
  before_action :set_main_page, only: [:show, :edit, :update, :destroy]

  # GET /main_pages
  # GET /main_pages.json
  def index
    @main_pages = MainPage.all
  end

  # GET /main_pages/1
  # GET /main_pages/1.json
  def show
  end

  # GET /main_pages/new
  def new
    @main_page = MainPage.new
  end

  # GET /main_pages/1/edit
  def edit
  end

  # POST /main_pages
  # POST /main_pages.json
  def create
    @main_page = MainPage.new(main_page_params)

    respond_to do |format|
      if @main_page.save
        format.html { redirect_to @main_page, notice: 'Main page was successfully created.' }
        format.json { render :show, status: :created, location: @main_page }
      else
        format.html { render :new }
        format.json { render json: @main_page.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /main_pages/1
  # PATCH/PUT /main_pages/1.json
  def update
    respond_to do |format|
      if @main_page.update(main_page_params)
        format.html { redirect_to @main_page, notice: 'Main page was successfully updated.' }
        format.json { render :show, status: :ok, location: @main_page }
      else
        format.html { render :edit }
        format.json { render json: @main_page.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /main_pages/1
  # DELETE /main_pages/1.json
  def destroy
    @main_page.destroy
    respond_to do |format|
      format.html { redirect_to main_pages_url, notice: 'Main page was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_main_page
      @main_page = MainPage.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def main_page_params
      params[:main_page]
    end
end

app/controllers/products_controller.rb
class ProductsController < ApplicationController
  before_action :set_product, only: [:show, :edit, :update, :destroy]

  # GET /products
  # GET /products.json
  def index
    
    if params[:tag]
    @products = current_user.products.tagged_with(params[:tag])
  else
    @products = current_user.products.all
  end
  end

  # GET /products/1
  # GET /products/1.json
  def show
    
  end

  # GET /products/new
  def new
    @product = current_user.products.new
  end

  # GET /products/1/edit
  def edit
  end

  # POST /products
  # POST /products.json
  def create
    @product = current_user.products.new(product_params)
    respond_to do |format|
      if @product.save
        UserMailer.delay(run_at: @product.guarantee_expiration).guarantee(current_user, @product)
        format.html { redirect_to @product, notice: 'Product was successfully created.' }
        format.json { render :show, status: :created, location: @product }
      else
        format.html { render :new }
        format.json { render json: @product.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /products/1
  # PATCH/PUT /products/1.json
  def update
    respond_to do |format|
      if @product.update(product_params)
        format.html { redirect_to @product, notice: 'Product was successfully updated.' }
        format.json { render :show, status: :ok, location: @product }
      else
        format.html { render :edit }
        format.json { render json: @product.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /products/1
  # DELETE /products/1.json
  def destroy
    @product.destroy
    respond_to do |format|
      format.html { redirect_to products_url, notice: 'Product was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_product
      @product = Product.friendly.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def product_params
      params.require(:product).permit(:name, :image, :guarantee_expiration, :tag_list)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/main_pages_helper.rb
module MainPagesHelper
end

app/helpers/products_helper.rb
module ProductsHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=Edge,chrome=1">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title><%= content_for?(:title) ? yield(:title) : "Gwarancje" %></title>
    <%= csrf_meta_tags %>

    <!-- Le HTML5 shim, for IE6-8 support of HTML elements -->
    <!--[if lt IE 9]>
      <script src="//cdnjs.cloudflare.com/ajax/libs/html5shiv/3.6.1/html5shiv.js" type="text/javascript"></script>
    <![endif]-->

    <%= stylesheet_link_tag "application", :media => "all" %>

    <!-- For third-generation iPad with high-resolution Retina display: -->
    <!-- Size should be 144 x 144 pixels -->
    <%= favicon_link_tag 'apple-touch-icon-144x144-precomposed.png', :rel => 'apple-touch-icon-precomposed', :type => 'image/png', :sizes => '144x144' %>

    <!-- For iPhone with high-resolution Retina display: -->
    <!-- Size should be 114 x 114 pixels -->
    <%= favicon_link_tag 'apple-touch-icon-114x114-precomposed.png', :rel => 'apple-touch-icon-precomposed', :type => 'image/png', :sizes => '114x114' %>

    <!-- For first- and second-generation iPad: -->
    <!-- Size should be 72 x 72 pixels -->
    <%= favicon_link_tag 'apple-touch-icon-72x72-precomposed.png', :rel => 'apple-touch-icon-precomposed', :type => 'image/png', :sizes => '72x72' %>

    <!-- For non-Retina iPhone, iPod Touch, and Android 2.1+ devices: -->
    <!-- Size should be 57 x 57 pixels -->
    <%= favicon_link_tag 'apple-touch-icon-precomposed.png', :rel => 'apple-touch-icon-precomposed', :type => 'image/png' %>

    <!-- For all other devices -->
    <!-- Size should be 32 x 32 pixels -->
    <%= favicon_link_tag 'favicon.ico', :rel => 'shortcut icon' %>

    <%= javascript_include_tag "application" %>
  </head>
  <body>

    <div class="navbar navbar-fluid-top">
      <div class="navbar-inner">
        <div class="container-fluid">
          <a class="btn btn-navbar" data-target=".nav-collapse" data-toggle="collapse">
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
          </a>
          <%= link_to 'Gwarancje', root_path, class: "brand" %>
          <div class="container-fluid nav-collapse">
            <ul class="nav">
              <li><%= link_to "Produkty", products_path  %></li>
              <li><%= link_to "Dodaj produkt", new_product_path  %></li>
            </ul>
          </div><!--/.nav-collapse -->
        </div>
      </div>
    </div>

    <div class="container-fluid">
      <div class="row-fluid">
        <div class="span3">
          <div class="well sidebar-nav">
            <ul class="nav nav-list">
              <li class="nav-header">Konto</li>
              <% if user_signed_in? %>
                  <li> <%= link_to current_user.email, edit_user_registration_path %> </li>
                  <li> <%= link_to 'Wyloguj', destroy_user_session_path, :method=>'delete' %> </li>
                <% else %>
                  <li> <%= link_to 'Logowanie', new_user_session_path %> </li>
                  <li> <%= link_to 'Rejestracja', new_user_registration_path %> </li>
                <% end -%>
            </ul>
          </div><!--/.well -->
        </div><!--/span-->
        <div class="span9">
          <%= bootstrap_flash %>
          <%= yield %>
        </div>
      </div><!--/row-->

      <footer>
        <p>&copy; Company 2014</p>
      </footer>

    </div> <!-- /container -->

  </body>
</html>

app/views/main_pages/_form.html.erb
<%= form_for(@main_page) do |f| %>
  <% if @main_page.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@main_page.errors.count, "error") %> prohibited this main_page from being saved:</h2>

      <ul>
      <% @main_page.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/main_pages/edit.html.erb
<h1>Editing main_page</h1>

<%= render 'form' %>

<%= link_to 'Show', @main_page %> |
<%= link_to 'Back', main_pages_path %>

app/views/main_pages/index.html.erb
<h1>Skrzynka na przedmioty</h1>

<table>
  <thead>
    
  </thead>

  <tbody>
    <br>
    <p>Ta strona umorzliwia ci przechowywanie produktów i kontrolę kiedy wygaśnie ich gwarancja</p>
  </tbody>
</table>

<br>

app/views/main_pages/new.html.erb
<h1>New main_page</h1>

<%= render 'form' %>

<%= link_to 'Back', main_pages_path %>

app/views/main_pages/show.html.erb
<p id="notice"><%= notice %></p>

<%= link_to 'Edit', edit_main_page_path(@main_page) %> |
<%= link_to 'Back', main_pages_path %>

app/views/products/_form.html.erb
<%= form_for @product, :html => { :class => 'form-horizontal' } do |f| %>
  <div class="control-group">
    <%= f.label :name, :class => 'control-label' %>
    <div class="controls">
      <%= f.text_field :name, :class => 'text_field' %>
    </div>
  </div>
  <div class="control-group">
    <%= f.label :image, :class => 'control-label' %>
    <div class="controls">
      <%= f.file_field :image, :class => 'file_field' %>
    </div>
  </div>
    
  <div class="control-group">
    <%= f.label :tag_list,"Tags (separated by commas)", :class => 'control-label' %>
    <div class="controls">
      <%= f.text_field :tag_list, :class => 'text_field' %>
    </div>
  </div>

  <div class="control-group">
    <%= f.label :guarantee_expiration, :class => 'control-label' %>
    <div class="controls">
      <%= f.date_select :guarantee_expiration, :class => 'text_field' %>
    </div>
  </div>

  <div class="form-actions">
    <%= f.submit nil, :class => 'btn btn-primary' %>
    <%= link_to t('.cancel', :default => t("helpers.links.cancel")),
                products_path, :class => 'btn' %>
  </div>
<% end %>

app/views/products/edit.html.erb
<%- model_class = Product -%>
<div class="page-header">
  <h1><%=t '.title', :default => [:'helpers.titles.edit', 'Edit %{model}'], :model => model_class.model_name.human.titleize %></h1>
</div>
<%= render :partial => 'form' %>

app/views/products/index.html.erb
<%- model_class = Product -%>
<div class="page-header">
  <h1><%=t '.title', :default => model_class.model_name.human.pluralize.titleize %></h1>
</div>
<table class="table table-striped">
  <thead>
    <tr>
      <th><%= model_class.human_attribute_name(:name) %></th>
      <th><%= model_class.human_attribute_name(:image) %></th>
      <th><%= model_class.human_attribute_name(:guarantee_expiration) %></th>
      <th><%= model_class.human_attribute_name(:tag) %></th>
      <th><%=t '.actions', :default => t("helpers.actions") %></th>
    </tr>
  </thead>
  <tbody>
    <% @products.each do |product| %>
      <tr>
        <td><%= link_to product.name, product_path(product) %></td>
        <td><%= image_tag product.image.url(:thumb) %></td>
        <td><%= product.guarantee_expiration %></td>
        <td><%= raw product.tags.map(&:name).map { |t| link_to t, tag_path(t) }.join(', ') %></td>
        <td>
          <%= link_to t('.edit', :default => t("helpers.links.edit")),
                      edit_product_path(product), :class => 'btn btn-mini' %>
          <%= link_to t('.destroy', :default => t("helpers.links.destroy")),
                      product_path(product),
                      :method => :delete,
                      :data => { :confirm => t('.confirm', :default => t("helpers.links.confirm", :default => 'Are you sure?')) },
                      :class => 'btn btn-mini btn-danger' %>
        </td>
      </tr>
    <% end %>
  </tbody>
</table>

<%= link_to t('.new', :default => t("helpers.links.new")),
            new_product_path,
            :class => 'btn btn-primary' %>

app/views/products/new.html.erb
<%- model_class = Product -%>
<div class="page-header">
  <h1><%=t '.title', :default => [:'helpers.titles.new', 'New %{model}'], :model => model_class.model_name.human.titleize %></h1>
</div>
<%= render :partial => 'form' %>

app/views/products/show.html.erb
<%- model_class = Product -%>
<div class="page-header">
  <h1><%=t '.title', :default => model_class.model_name.human.titleize %></h1>
</div>

<dl class="dl-horizontal">
  <dt><strong><%= model_class.human_attribute_name(:name) %>:</strong></dt>
  <dd><%= @product.name %></dd>
  <dt><strong><%= model_class.human_attribute_name(:image) %>:</strong></dt>
  <dd><%= image_tag @product.image.url(:medium) %></dd>
  <dt><strong><%= model_class.human_attribute_name(:guarantee_expiration) %>:</strong></dt>
  <dd><%= @product.guarantee_expiration %></dd>
  <dt><strong><%= model_class.human_attribute_name(:tags) %>:</strong></dt>
  <dd><%= raw @product.tag_list.map { |t| link_to t, tag_path(t) }.join(', ') %></dd>
</dl>

<div class="form-actions">
  <%= link_to t('.back', :default => t("helpers.links.back")),
              products_path, :class => 'btn'  %>
  <%= link_to t('.edit', :default => t("helpers.links.edit")),
              edit_product_path(@product), :class => 'btn' %>
  <%= link_to t('.destroy', :default => t("helpers.links.destroy")),
              product_path(@product),
              :method => 'delete',
              :data => { :confirm => t('.confirm', :default => t("helpers.links.confirm", :default => 'Are you sure?')) },
              :class => 'btn btn-danger' %>
</div>